# Generated by Django 5.0 on 2024-07-30 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_expenses_created_by_alter_expenseshare_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='split_method',
            field=models.CharField(choices=[('equal', 'Equal'), ('exact', 'Exact'), ('percentage', 'Percentage')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
